#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, r32f) readonly uniform image2D srcMip;
layout(set = 0, binding = 1, r32f) writeonly uniform image2D dstMip;

void main()
{
	const ivec2 dstCoord = ivec2(gl_GlobalInvocationID.xy);
	const ivec2 dstSize = imageSize(dstMip);
	if (any(greaterThanEqual(dstCoord, dstSize))) {
		return;
	}

	const ivec2 srcSize = imageSize(srcMip);
	const ivec2 srcBase = dstCoord * 2;
	const ivec2 c00 = min(srcBase, srcSize - ivec2(1));
	const ivec2 c10 = min(srcBase + ivec2(1, 0), srcSize - ivec2(1));
	const ivec2 c01 = min(srcBase + ivec2(0, 1), srcSize - ivec2(1));
	const ivec2 c11 = min(srcBase + ivec2(1, 1), srcSize - ivec2(1));

	const float d00 = imageLoad(srcMip, c00).r;
	const float d10 = imageLoad(srcMip, c10).r;
	const float d01 = imageLoad(srcMip, c01).r;
	const float d11 = imageLoad(srcMip, c11).r;
	imageStore(dstMip, dstCoord, vec4(min(min(d00, d10), min(d01, d11))));
}
