#!/usr/bin/env bash
# ProjectV KT documents — regen.sh
# Regenerate .tex from .md via pandoc (standalone + fragment for combined).
# Run from docs/tex/.

set -euo pipefail
cd "$(dirname "$0")"

# --- pandoc common options ---
# - gfm: GitHub-flavored markdown (tables, fenced code, autolinks)
# - listings: code blocks via listings package
# - --no-standalone for fragments (no preamble, no \begin{document})

PANDOC_COMMON=(
  --from "gfm+yaml_metadata_block+pipe_tables+raw_html+raw_attribute+tex_math_dollars"
  --to "latex"
  --no-highlight
  -V documentclass=article
  -V classoption="11pt,a4paper,oneside"
  -H header.tex
  --wrap=preserve
)

declare -A MD=(
  [KT-2.1_Architecture]=../KT-2.1_Architecture.md
  [KT-2.2_Test_Report]=../KT-2.2_Test_Report.md
  [KT-3.1_User_Guide]=../KT-3.1_User_Guide.md
  [KT-3.2_Final_Report]=../KT-3.2_Final_Report.md
)

declare -A YAML=(
  [KT-2.1_Architecture]=KT-2.1.yaml
  [KT-2.2_Test_Report]=KT-2.2.yaml
  [KT-3.1_User_Guide]=KT-3.1.yaml
  [KT-3.2_Final_Report]=KT-3.2.yaml
)

echo "==> Regenerating 4 .tex (standalone + fragment) from .md"

for name in "${!MD[@]}"; do
  src="${MD[$name]}"
  meta="${YAML[$name]}"
  out_tex="${name}.tex"
  out_frag="${name}-frag.tex"

  if [[ ! -f "$src" ]]; then
    echo "  SKIP $name: source $src not found" >&2
    continue
  fi
  if [[ ! -f "$meta" ]]; then
    echo "  SKIP $name: metadata $meta not found" >&2
    continue
  fi

  echo "  $src"
  echo "    → $out_tex (standalone, with title page)"
  pandoc "${PANDOC_COMMON[@]}" \
    --metadata-file="$meta" \
    -s -o "$out_tex" \
    "$src"

  echo "    → $out_frag (body-only fragment, for KT-Combined)"
  # Extract body (between \begin{document} and \end{document}) from standalone.
  # Use awk: skip lines until \begin{document}, then copy until \end{document}.
  awk '
    /^\\begin\{document\}/{flag=1; next}
    /^\\end\{document\}/{flag=0}
    flag
  ' "$out_tex" > "$out_frag"
  # Remove \maketitle (combined has its own title page; \title{} is in standalone preamble only).
  sed -i '/^\\maketitle$/d' "$out_frag"
  # Prefix \label{} with doc name to avoid "multiply defined" in combined.
  sed -i "s|\\\\label{|\\\\label{$name-|g" "$out_frag"

  # Post-process: .bmp → .png (we pre-converted screenshots via ffmpeg).
  # Apply to all 4 КТ (some may reference .bmp).
  if grep -q '\.bmp' "$out_tex"; then
    sed -i 's/\.bmp/.png/g' "$out_tex" "$out_frag"
    echo "    → sed: .bmp → .png (in $out_tex, $out_frag)"
  fi
done

# --- KT-Combined.tex (master: input all 4 fragments) ---
cat > KT-Combined.tex <<'EOF'
% ProjectV KT documents — Combined (master)
% Includes all 4 КТ fragments. Regenerated by regen.sh.

\documentclass[11pt,a4paper,oneside]{article}
\input{header.tex}
\begin{document}

\thispagestyle{plain}
\begin{center}
  {\Huge\bfseries ProjectV — Сборник контрольных точек}\\[12pt]
  {\Large КТ-2.1, КТ-2.2, КТ-3.1, КТ-3.2}\\[6pt]
  {\large 2026-06-13}
\end{center}
\vspace{1cm}
\tableofcontents
\clearpage

EOF

for name in KT-2.1_Architecture KT-2.2_Test_Report KT-3.1_User_Guide KT-3.2_Final_Report; do
  cat >> KT-Combined.tex <<EOF
\\clearpage
\\input{${name}-frag.tex}

EOF
done

cat >> KT-Combined.tex <<'EOF'
\end{document}
EOF

echo "  → KT-Combined.tex (master, includes 4 fragments)"
echo "==> Done. Run 'make' to compile all PDFs."
